### ISSUE TITLE
One question about the certified formula

### ISSUE THREAD

**Issue by ej0cl6** [lushleaf/Structure-free-certified-NLP#3]
Hi! I have one question about the certified formula. In the paper, you use
> delta(x) = g(X, y) - g(X, y_B) - 2*q_X > 0 

to certify the example.

However, in the code, the formula for certifying is
> result['acc'] - 1. + np.prod(tem_tv) >= 0.5 + args.mc_error

I got a little bit confused about these two. Could you give me some explanations?

**Comment by lushleaf** [comment]
Hi,

For the binary classification case:

g(X, y_B) = 1 - g(X,y) and thus 
g(X, y) - g(X, y_B) - 2*q_X > 0     <=>   2g(X, y) - 2*q_X > 1, which is given by the code.

For the case with more than two classes,
g(X, y_B) <= 1 - g(X,y) and thus 

g(X, y) - g(X, y_B) - 2*q_X >= g(X, y) - (1 - g(X, y)) - 2*q_X,

thus once 2g(X, y) - 2*q_X > 1 we must have g(X, y) - g(X, y_B) - 2*q_X >= 0.

The mc error is extra things need to be plus as we used Monte Carlo sample.

The real certified acc is actually no less than the certified acc returned by the code.

**Comment by ej0cl6** [comment]
Thank you so much!
